### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift,Ruby,Go & Python that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by eonist** [comment]
Hang loose my friend, I will add it. But first I have to support pull requests in the app I use to interact with github.

**Comment by korzonek** [comment]
@eonist thank you!!! :heart: 

BTW... we are currently working on support for pull requests in codebeat. Would you like to see interactive mockups of it and share feedback on it? 

Good, early feedback always helps prioritise things and save a lot of time in development :smile:

**Comment by eonist** [comment]
I thought github forbade bots on their network?

**Comment by korzonek** [comment]
Bots???

**Comment by eonist** [comment]
Your answers seemed a bit bot like. Sorry if I misinterpreted.

**Comment by eonist** [comment]
http://www.wired.com/2012/12/github-bots/

**Comment by korzonek** [comment]
:) Well... I like computers and code :)

Giphy

**Comment by eonist** [comment]
tick?

**Comment by korzonek** [comment]
Giphy

**Comment by eonist** [comment]
Ok. I guess i wont report you then ;) I tried to look through your website. I wish it was a bit easier to use. Like enter github url and get instant results.

**Comment by korzonek** [comment]
@eonist it works like that for public repositories :) You just need to cope https url from Github, codebeat will analyse repo and create report page e.g. https://codebeat.co/projects/github-com-eonist-swift-utils

**Comment by eonist** [comment]
I didnt find this option on your site. Onboarding is key ;). Also Your analysis is a bit off code duplication that is not really duplication, and static methods should be allowed to be numerouse in a class. Non static methods in a class should be kept to a minimum.

**Comment by eonist** [comment]
I like your app though. Cool concept if you get it the algorithms right.

**Comment by eonist** [comment]
Im planing to build something similar before summer. But its more about code analysis for utomatic git commits.

**Comment by eonist** [comment]
Are you guys using heuristics or a neural network for your analytics?

**Comment by marcinwyszynski** [comment]
Just heuristics for now but we're looking into using ML, too.

**Comment by eonist** [comment]
If I may ask, Where can i drop github urls to scan?

**Comment by marcinwyszynski** [comment]
Go through the 'Log in' flow. When asked whether you want to go Open Source or Private/Premium choose the first option and you can add any open source repo that's freely accessible from the wild wild web.

**Comment by eonist** [comment]
OK, awesome. I will.

**Comment by eonist** [comment]
added it.

**Comment by eonist** [comment]
@korzonek Are you guys on vacation or something? Ive been trying to contact you on intercom for a week now. Thanks

**Comment by eonist** [comment]
@korzonek I paid for the service, But still cant add private repos? And your not answering emails 🙁

**Comment by marcinwyszynski** [comment]
I haven't worked for codebeat for more than two years at this point but you can try [reaching the CEO through LinkedIn](https://www.linkedin.com/in/korzeniowski/), which he's perhaps more likely to check?

**Comment by korzonek** [comment]
@eonist I missed your email 😔Sorry! I will ping you at the email on your GitHub profile.

**Pull request closed without merging**
